import type { Locale } from "./locales";

/**
 * UI phrase dictionary for server-rendered pages. Exact phrase matching means
 * customer names, product names and message text remain untouched.
 */
export const AUTO_TRANSLATIONS: Record<Exclude<Locale, "ru">, Record<string, string>> = {
  en: {
    "Добро пожаловать в DELIS 👋": "Welcome to DELIS 👋",
    "Дашборд": "Dashboard", "Обзор": "Overview", "Продажи": "Sales", "Коммуникации": "Communications", "Каналы": "Channels", "Управление": "Management",
    "Заказы": "Orders", "Новый заказ": "New order", "Все заказы": "All orders", "Товары": "Products", "Склад": "Warehouse", "Поставщики": "Suppliers", "Клиенты": "Customers", "Агенты": "Agents", "Маркетинг и Акции": "Marketing & Promotions", "Доставка": "Delivery", "Возвраты": "Returns",
    "Онлайн-чат": "Live chat", "Рассылки": "Broadcasts", "Уведомления": "Notifications", "Сайт": "Website", "Финансы": "Finance", "Настройки": "Settings", "Интеграции": "Integrations", "База знаний": "Knowledge Base", "Аналитика": "Analytics", "Задачи": "Tasks", "Пользователи и RBAC": "Users & RBAC",
    "Выручка": "Revenue", "Прибыль": "Profit", "Расходы": "Expenses", "Остаток склада": "Stock balance", "Средний чек": "Average order value", "Конверсия": "Conversion", "Маржа": "Margin",
    "Создать": "Create", "Добавить": "Add", "Сохранить": "Save", "Отмена": "Cancel", "Закрыть": "Close", "Удалить": "Delete", "Изменить": "Edit", "Открыть": "Open", "Экспорт XLSX": "Export XLSX", "Экспорт": "Export", "Импорт Excel / CSV": "Import Excel / CSV", "Скачать шаблон": "Download template",
    "Статус": "Status", "Дата": "Date", "Сумма": "Amount", "Клиент": "Customer", "Товар": "Product", "Категория": "Category", "Канал": "Channel", "Оплата": "Payment", "Комментарий": "Comment", "Количество": "Quantity", "Цена": "Price", "Регион": "Region", "Город": "City", "Телефон": "Phone", "Действия": "Actions",
    "Все": "All", "Все каналы": "All channels", "Все категории": "All categories", "Все источники": "All sources", "Поиск": "Search", "Глобальный поиск…": "Global search…", "Поиск по номеру или клиенту": "Search by number or customer", "Поиск по названию, SKU, штрихкоду": "Search by name, SKU, barcode",
    "Активен": "Active", "Черновик": "Draft", "Архив": "Archived", "В работе": "In progress", "Выполнено": "Completed", "К выполнению": "To do", "Просрочено": "Overdue", "Срочно": "Urgent", "Обычная": "Normal", "Не срочно": "Low priority", "Не назначен": "Unassigned",
    "Приход": "Inbound", "Расход": "Outbound", "Перемещение": "Transfer", "Списание": "Write-off", "Инвентаризация": "Inventory count", "Критические остатки": "Critical stock", "История движений": "Movement history", "Остатки по товарам": "Stock by product",
    "Поставщики и Закупки": "Suppliers & Procurement", "Создать закупку": "Create purchase", "Заказать одним кликом": "Order in one click", "Заказать у поставщика": "Order from supplier", "Принять": "Receive", "Ожидается": "Expected", "просрочка": "overdue",
    "Курьеры": "Couriers", "Назначить доставку": "Assign delivery", "Доставлен": "Delivered", "Свободен": "Available", "Занят": "Busy", "Оффлайн": "Offline", "Лента доставок": "Delivery feed",
    "Оформить возврат": "Create return", "История возвратов": "Return history", "Причина": "Reason", "Ожидают решения": "Awaiting decision", "Возвращено": "Refunded", "Возврат ₽": "Refund", "+ склад": "+ stock",
    "Промокоды и скидки": "Promo codes & discounts", "Автоматические триггеры": "Automated triggers", "Рекламные каналы и ROI": "Ad channels & ROI", "Создать промокод": "Create promo code", "Скидка": "Discount", "Использовано": "Used", "Действует до": "Valid until", "Бессрочно": "Unlimited",
    "Массовые рассылки": "Mass broadcasts", "Аудитория": "Audience", "Сообщение": "Message", "Шаблоны": "Templates", "Медиа для рассылки": "Media for broadcast", "Предпросмотр": "Preview", "Отправка": "Sending", "Сейчас": "Now", "Отложить": "Schedule", "Запланировать": "Schedule", "История рассылок": "Broadcast history", "Кампания": "Campaign", "Автор": "Author", "Отправлена": "Sent", "Запланирована": "Scheduled",
    "Мой аккаунт": "My account", "Логин для входа": "Sign-in login", "Пароль": "Password", "Сменить": "Change", "Сменить пароль": "Change password", "Сменить логин": "Change login", "Текущий пароль": "Current password", "Новый пароль (мин. 4 символа)": "New password (min. 4 characters)", "Текущий логин": "Current login", "Новый логин": "New login", "Язык интерфейса": "Interface language", "Уведомления в Telegram": "Telegram notifications",
    "Наличные": "Cash", "Касса (наличные)": "Cash register", "Приём наличных": "Cash in", "Инкассация": "Collection", "Новая операция": "New operation", "Денежный поток": "Cash flow", "История операций": "Operation history",
    "P&L Отчёт о прибылях и убытках": "P&L Profit and Loss Statement", "Чистая прибыль": "Net profit", "Валовая прибыль": "Gross profit", "Себестоимость": "Cost of goods", "Структура прибыли": "Profit structure", "Экспорт в Excel": "Export to Excel",
    "Сохранить SEO": "Save SEO", "Опубликовать": "Publish", "Страницы сайта": "Website pages", "SEO и метаданные": "SEO & metadata", "Управление сайтом": "Website management", "Создать публикацию": "Create post", "Контент-план": "Content plan", "Баннеры": "Banners",
    "Торговые точки, GPS и Фотоотчёты": "Retail points, GPS & Photo reports", "GPS-карта": "GPS map", "Чат с агентом": "Chat with agent", "Сравнение агентов": "Compare agents", "Выполнение плана": "Plan completion", "Комиссия": "Commission", "Визиты": "Visits", "К выплате": "Payout",
    "Счёт A4": "Invoice A4", "Накладная": "Waybill", "Чек 80мм": "Receipt 80mm", "Акт сверки": "Reconciliation", "Печать / PDF": "Print / PDF",
  },
  uz: {
    "Добро пожаловать в DELIS 👋": "DELIS'ga xush kelibsiz 👋",
    "Дашборд": "Boshqaruv paneli", "Обзор": "Umumiy", "Продажи": "Sotuvlar", "Коммуникации": "Aloqa", "Каналы": "Kanallar", "Управление": "Boshqaruv",
    "Заказы": "Buyurtmalar", "Новый заказ": "Yangi buyurtma", "Все заказы": "Barcha buyurtmalar", "Товары": "Mahsulotlar", "Склад": "Ombor", "Поставщики": "Yetkazib beruvchilar", "Клиенты": "Mijozlar", "Агенты": "Agentlar", "Маркетинг и Акции": "Marketing va Aksiyalar", "Доставка": "Yetkazib berish", "Возвраты": "Qaytarishlar",
    "Онлайн-чат": "Onlayn chat", "Рассылки": "Xabarnomalar", "Уведомления": "Bildirishnomalar", "Сайт": "Veb-sayt", "Финансы": "Moliya", "Настройки": "Sozlamalar", "Интеграции": "Integratsiyalar", "База знаний": "Bilimlar bazasi", "Аналитика": "Analitika", "Задачи": "Vazifalar", "Пользователи и RBAC": "Foydalanuvchilar va RBAC",
    "Выручка": "Daromad", "Прибыль": "Foyda", "Расходы": "Xarajatlar", "Средний чек": "O'rtacha chek", "Конверсия": "Konversiya", "Маржа": "Marja", "Остаток склада": "Ombor qoldig'i",
    "Создать": "Yaratish", "Добавить": "Qo'shish", "Сохранить": "Saqlash", "Отмена": "Bekor qilish", "Закрыть": "Yopish", "Удалить": "O'chirish", "Изменить": "Tahrirlash", "Открыть": "Ochish", "Экспорт": "Eksport",
    "Статус": "Holat", "Дата": "Sana", "Сумма": "Summa", "Клиент": "Mijoz", "Товар": "Mahsulot", "Категория": "Kategoriya", "Канал": "Kanal", "Оплата": "To'lov", "Комментарий": "Izoh", "Количество": "Miqdor", "Цена": "Narx", "Регион": "Hudud", "Город": "Shahar", "Телефон": "Telefon", "Действия": "Amallar",
    "Все": "Barchasi", "Все каналы": "Barcha kanallar", "Все категории": "Barcha kategoriyalar", "Все источники": "Barcha manbalar", "Поиск": "Qidiruv", "Глобальный поиск…": "Global qidiruv…", "Поиск по номеру или клиенту": "Raqam yoki mijoz bo'yicha qidirish", "Поиск по названию, SKU, штрихкоду": "Nomi, SKU yoki shtrix-kod bo'yicha qidirish",
    "Активен": "Faol", "Черновик": "Qoralama", "Архив": "Arxiv", "В работе": "Bajarilmoqda", "Выполнено": "Bajarildi", "К выполнению": "Bajarilishi kerak", "Просрочено": "Muddati o'tgan", "Срочно": "Shoshilinch", "Обычная": "Oddiy", "Не срочно": "Shoshilinch emas", "Не назначен": "Tayinlanmagan",
    "Приход": "Kirim", "Расход": "Chiqim", "Перемещение": "Ko'chirish", "Списание": "Hisobdan chiqarish", "Инвентаризация": "Inventarizatsiya", "Критические остатки": "Kritik qoldiqlar", "История движений": "Harakatlar tarixi", "Остатки по товарам": "Mahsulotlar bo'yicha qoldiq",
    "Поставщики и Закупки": "Yetkazib beruvchilar va Xaridlar", "Создать закупку": "Xarid yaratish", "Заказать одним кликом": "Bir bosishda buyurtma", "Заказать у поставщика": "Yetkazib beruvchidan buyurtma", "Принять": "Qabul qilish", "Ожидается": "Kutilmoqda", "просрочка": "kechikish",
    "Курьеры": "Kuryerlar", "Назначить доставку": "Yetkazishni tayinlash", "Доставлен": "Yetkazildi", "Свободен": "Bo'sh", "Занят": "Band", "Оффлайн": "Oflayn", "Лента доставок": "Yetkazishlar lentasi",
    "Оформить возврат": "Qaytarishni rasmiylashtirish", "История возвратов": "Qaytarishlar tarixi", "Причина": "Sabab", "Ожидают решения": "Qaror kutilmoqda", "Возвращено": "Qaytarildi", "Возврат ₽": "Pul qaytarish", "+ склад": "+ ombor",
    "Промокоды и скидки": "Promokodlar va chegirmalar", "Автоматические триггеры": "Avtomatik triggerlar", "Рекламные каналы и ROI": "Reklama kanallari va ROI", "Создать промокод": "Promokod yaratish", "Скидка": "Chegirma", "Использовано": "Ishlatilgan", "Действует до": "Amal qiladi", "Бессрочно": "Muddatsiz",
    "Массовые рассылки": "Ommaviy xabarnomalar", "Аудитория": "Auditoriya", "Сообщение": "Xabar", "Шаблоны": "Shablonlar", "Медиа для рассылки": "Xabarnoma uchun media", "Предпросмотр": "Ko'rib chiqish", "Отправка": "Yuborish", "Сейчас": "Hozir", "Отложить": "Keyinroq", "Запланировать": "Rejalashtirish", "История рассылок": "Xabarnomalar tarixi", "Кампания": "Kampaniya", "Автор": "Muallif", "Отправлена": "Yuborilgan", "Запланирована": "Rejalashtirilgan",
    "Мой аккаунт": "Mening akkauntim", "Логин для входа": "Kirish uchun login", "Пароль": "Parol", "Сменить": "O'zgartirish", "Сменить пароль": "Parolni o'zgartirish", "Сменить логин": "Loginni o'zgartirish", "Текущий пароль": "Joriy parol", "Новый пароль (мин. 4 символа)": "Yangi parol (kamida 4 belgi)", "Текущий логин": "Joriy login", "Новый логин": "Yangi login", "Язык интерфейса": "Interfeys tili", "Уведомления в Telegram": "Telegram bildirishnomalari",
    "Наличные": "Naqd", "Касса (наличные)": "Kassa (naqd)", "Приём наличных": "Naqd qabul qilish", "Инкассация": "Inkassatsiya", "Новая операция": "Yangi operatsiya", "Денежный поток": "Pul oqimi", "История операций": "Operatsiyalar tarixi",
    "P&L Отчёт о прибылях и убытках": "P&L Foyda va zarar hisoboti", "Чистая прибыль": "Sof foyda", "Валовая прибыль": "Yalpi foyda", "Себестоимость": "Tannarx", "Структура прибыли": "Foyda tuzilishi", "Экспорт в Excel": "Excelga eksport",
    "Сохранить SEO": "SEO saqlash", "Опубликовать": "Nashr qilish", "Страницы сайта": "Sayt sahifalari", "SEO и метаданные": "SEO va metama'lumotlar", "Управление сайтом": "Sayt boshqaruvi", "Создать публикацию": "Nashr yaratish", "Контент-план": "Kontent-reja", "Баннеры": "Bannerlar",
    "Торговые точки, GPS и Фотоотчёты": "Savdo nuqtalari, GPS va Foto hisobotlar", "GPS-карта": "GPS xarita", "Чат с агентом": "Agent bilan chat", "Сравнение агентов": "Agentlarni taqqoslash", "Выполнение плана": "Reja bajarilishi", "Комиссия": "Komissiya", "Визиты": "Tashriflar", "К выплате": "To'lanadigan",
    "Счёт A4": "Hisob A4", "Накладная": "Yuk xati", "Чек 80мм": "Chek 80mm", "Акт сверки": "Solishtirma dalolatnoma", "Печать / PDF": "Chop etish / PDF",
  },
};
