import { getOrder, getCustomerOrders } from "@/server/queries";
import { notFound } from "next/navigation";
import { PrintToolbar } from "@/app/print/PrintToolbar";

type L = "ru" | "uz" | "en";
const T: Record<L, Record<string, string>> = {
  ru: { title:"АКТ СВЕРКИ", period:"Период", supplier:"Поставщик", buyer:"Покупатель", shipped:"Отгружено", paid:"Оплачено", debt:"Задолженность", overpayment:"Переплата", history:"История операций", order:"Заказ", operation:"Операция", status:"Статус", debit:"Дебет", credit:"Кредит", total:"ИТОГО", supplierSign:"От поставщика", buyerSign:"От покупателя", print:"Печать / PDF", invoice:"Заказ товаров", paidStatus:"Оплачен", pending:"Ожидает", cancelled:"Отменён" },
  uz: { title:"SOLISHTIRMA DALOLATNOMA", period:"Davr", supplier:"Yetkazib beruvchi", buyer:"Xaridor", shipped:"Jo'natilgan", paid:"To'langan", debt:"Qarzdorlik", overpayment:"Ortiqcha to'lov", history:"Operatsiyalar tarixi", order:"Buyurtma", operation:"Operatsiya", status:"Holat", debit:"Debet", credit:"Kredit", total:"JAMI", supplierSign:"Yetkazib beruvchidan", buyerSign:"Xaridordan", print:"Chop etish / PDF", invoice:"Mahsulot buyurtmasi", paidStatus:"To'langan", pending:"Kutilmoqda", cancelled:"Bekor qilingan" },
  en: { title:"RECONCILIATION STATEMENT", period:"Period", supplier:"Supplier", buyer:"Buyer", shipped:"Shipped", paid:"Paid", debt:"Outstanding balance", overpayment:"Overpayment", history:"Transaction history", order:"Order", operation:"Operation", status:"Status", debit:"Debit", credit:"Credit", total:"TOTAL", supplierSign:"Supplier signature", buyerSign:"Buyer signature", print:"Print / PDF", invoice:"Goods order", paidStatus:"Paid", pending:"Pending", cancelled:"Cancelled" },
};
const num=(n:number)=>Math.round(n).toLocaleString("ru-RU");

export const dynamic = "force-dynamic";

export default async function ReconciliationPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{lang?:string}>}) {
  const {id}=await params; const sp=await searchParams; const lang:L=sp.lang==="uz"||sp.lang==="en"?sp.lang:"ru"; const t=T[lang];
  const data=await getOrder(Number(id)); if(!data) notFound(); const {order,customer}=data; if(!customer) notFound();
  const all=await getCustomerOrders(customer.id);
  const debit=all.reduce((s,o)=>s+Number(o.total),0);
  const paid=all.filter(o=>["paid","delivered"].includes(o.status)).reduce((s,o)=>s+Number(o.total),0);
  const balance=debit-paid;
  const date=(v:Date|string)=>new Date(v).toLocaleDateString(lang==="uz"?"uz-UZ":lang==="en"?"en-GB":"ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"});
  const first=all[0]?.createdAt??order.createdAt;
  const st=(s:string)=>["paid","delivered"].includes(s)?t.paidStatus:s==="cancelled"?t.cancelled:t.pending;
  const css=`
  .rec{max-width:800px;margin:24px auto;background:#fff;color:#1a1a2e;border-radius:16px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.25);font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.rec-head{background:linear-gradient(135deg,#1e1b4b,#4c1d95 65%,#7c3aed);color:#fff;padding:30px 36px;display:flex;justify-content:space-between}.rec-head h1{font-size:24px;margin:0}.rec-head p{font-size:11px;opacity:.75;margin-top:7px}.rec-body{padding:30px 36px}.parties{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:22px}.party{padding:14px;border-radius:12px;background:#f8f7ff;border:1px solid #e5e3ff}.party h4{font-size:9px;color:#7c3aed;text-transform:uppercase;letter-spacing:1px;margin-bottom:7px}.party p{font-size:12px;line-height:1.6}.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:24px}.kpi{padding:14px;border-radius:12px;background:#f8f7ff;border:1px solid #e5e3ff}.kpi label{display:block;font-size:9px;color:#666;text-transform:uppercase;letter-spacing:1px}.kpi strong{font-size:17px;color:#1e1b4b;display:block;margin-top:5px}table{width:100%;border-collapse:collapse}.rec h3{font-size:15px;margin:18px 0 10px}.rec th{background:#f8f7ff;color:#7c3aed;font-size:9px;letter-spacing:1px;text-transform:uppercase;text-align:left;padding:9px;border-bottom:2px solid #e5e3ff}.rec td{padding:10px 9px;border-bottom:1px solid #eee;font-size:12px}.r{text-align:right}.c{text-align:center}.rec tfoot td{font-weight:700;background:#f8f7ff;border-top:2px solid #e5e3ff}.signs{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:30px}.sign{text-align:center}.line{height:28px;border-bottom:1.5px solid #1e1b4b;margin-bottom:6px}.cap{font-size:9px;color:#999}.foot{text-align:center;border-top:1px solid #eee;margin-top:22px;padding:14px;color:#aaa;font-size:10px}@media print{.no-print{display:none!important}.rec{box-shadow:none;border-radius:0;margin:0}.rec-body{padding:20px 30px}}
  `;
  return <><style>{css}</style><PrintToolbar title={`${t.title} ${order.number}`} orderId={order.id}/><main className="rec"><header className="rec-head"><div><h1>{t.title}</h1><p>{t.period}: {date(first)} — {date(new Date())}</p></div><div style={{textAlign:"right"}}><div style={{fontSize:24,fontWeight:800}}>DELIS</div><p>{t.order} {order.number}</p></div></header><section className="rec-body"><div className="parties"><div className="party"><h4>{t.supplier}</h4><p><b>ООО «DELIS CHEMICALS»</b><br/>TIN 302 456 789<br/>+998 71 200-70-70</p></div><div className="party"><h4>{t.buyer}</h4><p><b>{customer.firstName} {customer.lastName}</b><br/>{customer.city}<br/>{customer.phone}</p></div></div><div className="kpis"><div className="kpi"><label>{t.shipped}</label><strong>{num(debit)} {lang==="en"?"UZS":"сум"}</strong></div><div className="kpi"><label>{t.paid}</label><strong style={{color:"#22c55e"}}>{num(paid)} {lang==="en"?"UZS":"сум"}</strong></div><div className="kpi"><label>{balance>0?t.debt:t.overpayment}</label><strong style={{color:balance>0?"#ef4444":"#22c55e"}}>{num(Math.abs(balance))} {lang==="en"?"UZS":"сум"}</strong></div></div><h3>{t.history}</h3><table><thead><tr><th>{t.date}</th><th>{t.order}</th><th>{t.operation}</th><th>{t.status}</th><th className="r">{t.debit}</th><th className="r">{t.credit}</th></tr></thead><tbody>{all.map(o=>{const isPaid=["paid","delivered"].includes(o.status);return <tr key={o.id}><td>{date(o.createdAt)}</td><td>{o.number}</td><td>{t.invoice}</td><td>{st(o.status)}</td><td className="r">{num(Number(o.total))}</td><td className="r">{isPaid?num(Number(o.total)):"—"}</td></tr>})}</tbody><tfoot><tr><td colSpan={4}>{t.total}</td><td className="r">{num(debit)}</td><td className="r">{num(paid)}</td></tr></tfoot></table><div className="signs"><div className="sign"><div className="line"/><div className="cap">{t.supplierSign}</div></div><div className="sign"><div className="line"/><div className="cap">{t.buyerSign}</div></div></div><footer className="foot">DELIS CRM · {date(new Date())}</footer></section></main></>;
}
